version: '3.8'

services:
  app:
    build: .
    container_name: text-summarizer
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - nltk_data:/usr/local/nltk_data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - FLASK_RUN_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nltk_data:
